apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: scdb-ingress
  labels:
    app: scdb
    tier: website
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
spec:
  tls:
  - hosts:
    - scunpacked.com
    - www.scunpacked.com
    secretName: scdb-tls
  rules:
  - host: scunpacked.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: scdb-website
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: scdb-api
            port:
              number: 80
